### PR TITLE
add thumbsup command

### PR DESCRIPTION
**Pull request by kindlychung**
i've found the :+1:  emoji to be the most frequently used reaction in my circles. so added a command and shortcut for it. 

thanks for your nice work!

### CODE REVIEW

**Comment by boxdot** [comment]
This is a good idea. I think @hrdl-github is right about making it more configurable. @kindlychung we can merge your work and adjust it in a follow-up or immediately change it here. WDYT?

**Comment by kindlychung** [comment]
I like that idea, too, but let's do it in a followup. Thanks!

**Comment by boxdot** [comment]
@kindlychung There are unfortunately merge conflicts now. Could you please resolve them? Then we can merge this MR.

**Comment by boxdot** [comment]
Thank you @kindlychung for the great idea. I merged #330 by @hrdl-github which implements this idea in a slightly more flexible way.

**Pull request closed without merging**
