### PR TITLE
Replace log4rs with tracing

### LINKED ISSUE #158: Replace log4rs by tracing
Rationale:

1. I am more familiar with tracing.
2. This removes the traitobject dependency having a security issue.

### PR DESCRIPTION
**Pull request by mucinoab**
Fixes #158

### CODE REVIEW

**Comment by boxdot** [comment]
Thank you!

**Review by boxdot — APPROVED** [review]

**Comment by mucinoab** [comment]
I am not quite sure what to do about the conflicts... 😞

**Comment by boxdot** [comment]
> I am not quite sure what to do about the conflicts... 😞

You can just check out `Cargo.lock` from the master branch, and then run e.g. `cargo check` again. It will generate a new fitting `Cargo.lock`.

**Comment by boxdot** [comment]
@mucinoab I merged the master and resolved the conflicts. Also removed a dbg statement. Ready to merge!

**Pull request merged**
