### PR TITLE
Bump presage to fad83ed

### PR DESCRIPTION
**Pull request by hrdl-github**

### CODE REVIEW

**Comment by gferon** [comment]
> Right now this is not sufficient to allow sending with the most recent presage version, as various operations fail with 401 unauthorized or 428 precondition required. I also see some `ERROR presage::manager::registered: error opening envelope, message will be skipped! error=Protocol error: message with old counter ?/?` messages, which might also be due to switching back and fourth between presage versions. I don't have a lot of time or a good understanding of `libsignal-service-rs` yet, so this may take a while to investigate.

Thanks for testing, this is actually helpful! I'll try to reproduce this error and see if we can fix it once and for all.

**Comment by gferon** [comment]
@hrdl-github could you maybe run `RUST_LOG=libsignal=trace,presage=trace gurk-rs -v` until the error happens and send me some logs (can be in private, on Matrix for example or by email).

**Comment by boxdot** [comment]
Old counter error points to a violation of the signal protocol. I would propose to relink. This will clear all signal sessions and reinitialize them again.

**Comment by gferon** [comment]
Superseded by https://github.com/boxdot/gurk-rs/pull/326

**Pull request closed without merging**
