### PR TITLE
chore: update presage

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by gertjanvanzwieten** [comment]
I just tried this out and almost all problems are gone: I can link again and send and receive messages from the laptop. The only issue now is that I don't see on my phone the messages that were sent from my computer, even though they do arrive at the recipient.

**Comment by boxdot** [comment]
@gertjanvanzwieten Thank you for testing!

> The only issue now is that I don't see on my phone the messages that were sent from my computer, even though they do arrive at the recipient.

This is a known issue. I tried to pin point this bug in presage and libservice-signal. No luck so far. @gferon Maybe we could pair on this, wdyt?

I will merge this PR because this is already good step forwards. Thanks to the maintainers of presage for fixing the bugs.

**Comment by gferon** [comment]
> This is a known issue. I tried to pin point this bug in presage and libservice-signal. No luck so far. @gferon Maybe we could pair on this, wdyt?

Let's do it 💪🏼

**Comment by gertjanvanzwieten** [comment]
A good step forwards for sure!

**Pull request merged**
